[project]
name = "marsrover-c373team1"
version = "0.2.0"
requires-python = ">=3.10"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"

[tool.coverage.run]
branch = true
source = ["marsrover"]

[tool.setuptools.packages.find]
include = ["marsrover"]
